"""Export chord progression results into ChordPro, plain text, CSV, and JSON sidecar."""

from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import TextIO

from chordscout.guitar import get_guitar_chord
from chordscout.models import AnalysisResult, format_timestamp


def export_plain_text(result: AnalysisResult) -> str:
    """Generate a clean, human-readable guitar chord chart."""
    meta = result.metadata
    lines: list[str] = [
        f"# Chord Progression for: {meta.file_name}",
        f"# Duration: {format_timestamp(meta.duration)}",
        f"# Estimated Key: {meta.key_estimate or 'N/A'}",
        f"# Estimated Tempo: {meta.tempo_bpm or 'N/A'} BPM",
        f"# Tuning Offset: {meta.tuning_offset_cents:+0.1f} cents",
        f"# Note: {result.disclaimer}",
        "",
        "--- CHORD PROGRESSION ---",
    ]

    for seg in result.segments:
        start_str = format_timestamp(seg.start_time, include_ms=True)
        end_str = format_timestamp(seg.end_time, include_ms=True)
        conf_str = f"({int(seg.confidence * 100)}%)" if seg.chord != "N" else ""
        edited_mark = " *" if seg.is_user_edited else ""
        lines.append(f"{start_str} - {end_str}   {seg.chord:<7} {conf_str}{edited_mark}")

    unique = result.unique_chords()
    if unique:
        lines.append("")
        lines.append("--- GUITAR CHORDS REFERENCE (Standard Tuning: E A D G B e) ---")
        for c in unique:
            gc = get_guitar_chord(c)
            if gc:
                lines.append(f"  {c:<6} : {gc.string_display}  (Base fret: {gc.base_fret})")
            else:
                lines.append(f"  {c:<6} : [custom voicing]")

    return "\n".join(lines)


def export_chordpro(result: AnalysisResult) -> str:
    """Export to ChordPro standard format (.cho / .chordpro)."""
    meta = result.metadata
    lines: list[str] = [
        f"{{title: {meta.file_name}}}",
    ]
    if meta.key_estimate:
        lines.append(f"{{key: {meta.key_estimate}}}")
    if meta.tempo_bpm:
        lines.append(f"{{tempo: {int(meta.tempo_bpm)}}}")
    lines.append(f"{{comment: Generated by ChordScout ({result.disclaimer})}}")
    lines.append("")

    # Output chords in lines grouped into bars/measures (~4 chords per line)
    current_line_chords: list[str] = []
    for i, seg in enumerate(result.segments):
        if seg.chord and seg.chord != "N":
            current_line_chords.append(f"[{seg.chord}]")
        else:
            current_line_chords.append("---")

        if len(current_line_chords) >= 4 or i == len(result.segments) - 1:
            timestamp = format_timestamp(result.segments[max(0, i - len(current_line_chords) + 1)].start_time)
            lines.append(f"{{comment: {timestamp}}} " + "  ".join(current_line_chords))
            current_line_chords = []

    # Include chord definitions in ChordPro format
    unique = result.unique_chords()
    if unique:
        lines.append("")
        lines.append("{comment: Guitar Chord Definitions}")
        for c in unique:
            gc = get_guitar_chord(c)
            if gc:
                fret_str = "".join("x" if f == -1 else str(f) for f in gc.frets)
                lines.append(f"{{define: {c} frets {fret_str} base-fret {gc.base_fret}}}")

    return "\n".join(lines)


def export_csv(result: AnalysisResult, file_or_buffer: TextIO | Path | str) -> None:
    """Export chord progression segments to CSV format."""
    should_close = False
    if isinstance(file_or_buffer, (str, Path)):
        f = open(file_or_buffer, "w", newline="", encoding="utf-8")
        should_close = True
    else:
        f = file_or_buffer

    try:
        writer = csv.writer(f)
        writer.writerow(["start_time", "end_time", "duration", "chord", "confidence", "is_user_edited"])
        for seg in result.segments:
            writer.writerow([
                round(seg.start_time, 3),
                round(seg.end_time, 3),
                round(seg.duration, 3),
                seg.chord,
                round(seg.confidence, 3),
                seg.is_user_edited,
            ])
    finally:
        if should_close:
            f.close()


def save_project(result: AnalysisResult, target_path: Path | str) -> None:
    """Save an analysis result to a JSON sidecar file (.chordscout.json)."""
    data = result.to_dict()
    with open(target_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)


def load_project(source_path: Path | str) -> AnalysisResult:
    """Load an analysis result from a JSON sidecar file (.chordscout.json)."""
    with open(source_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return AnalysisResult.from_dict(data)
